config/routes.rb
Rails.application.routes.draw do

  resources :event_types, except: %i(show)

  devise_for :attendees, controllers: { registrations: 'registrations' }
  scope "attendees" do
    get :agenda, to: 'attendees#agenda', as: :attendee_agenda
  end
  resources :attendees, only: %i() do
    resources :slots, only: %i() do
      member do
        put :cancel
      end
    end
  end

  scope module: 'administration', as: 'admin', path: 'admin' do
    get 'dashboard/index', as: :dashboard
    get 'dashboard/settings', as: :settings
    patch 'settings', to: 'settings#update', as: :update_settings
    delete 'delete_image', to: 'settings#delete_image'
    resources :servers, except: :show
    resources :users, except: :show
    authenticate :admin do
      require 'sidekiq/web'
      mount Sidekiq::Web => '/sidekiq'
    end
  end
  devise_for :admins

  resources :user, param: :slug do
    resources :user_attendees, as: :attendees
    get '/', to: 'users#profile', as: :profile
    get '/agenda', to: 'users#agenda', as: :agenda
    get '/events', to: 'users#events', as: :user_events
  end
  scope "user/:slug" do
    resources :slots, except: %i(index) do
      member do
        put :cancel
        get :book
        patch :booking
      end
    end
  end

  resources :servers, only: %i(index show), constraints: { format: :json }

  # Used by server connection of other servers
  get 'users', to: 'users#index', constraints: { format: :json }

  devise_for :users, controllers: { registrations: 'registrations' }
  devise_scope :user do
    delete 'delete_image', to: 'registrations#delete_image'
  end
  get 'home', to: 'home#index'
  get 'privacy', to: 'home#privacy', as: :privacy
  get 'legal', to: 'home#legal', as: :legal
  get 'tos', to: 'home#tos', as: :tos
  get 'credits', to: 'home#credits', as: :credits
  get 'security', to: 'home#security', as: :security
  get 'agenda', to: 'home#agenda', as: :agenda
  get 'decentralize', to: 'home#decentralize', as: :decentralize
  root to: "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/slot.rb
require 'action_view'

class Slot < ApplicationRecord
  include ActionView::Helpers::DateHelper

  BEHAVE_NEUTRAL = 'neutral'.freeze

  belongs_to :user
  belongs_to :attendee, required: false
  belongs_to :event_type, required: true

  validates :date_start, :date_end, presence: true

  scope :free, -> { where(attendee_id: nil).joins(:event_type).where(event_types: { is_available: true }) }
  scope :taken, -> { where('attendee_id IS NOT NULL') }
  scope :in_future, -> { where('date_start > ?', DateTime.now) }

  has_rich_text :notes

  def title(is_attendee = false)
    duration = distance_of_time_in_words(date_end, date_start)
    if attendee.blank?
      "#{date_start.strftime('%H:%M')} - #{duration}"
    else
      is_attendee = is_attendee.blank? ? false : is_attendee[:is_attendee]
      is_attendee ? user.lastname : "#{attendee.name} - #{duration}"
    end
  end

  def as_json(is_attendee = false)
    {
      id: id,
      title: title(is_attendee),
      start: date_start,
      end: date_end,
      user: user.name,
      event_type: event_type&.label,
      event_color: event_type&.color,
      extendedProps: {
        has_attendee: !attendee.blank?,
        attendee_id: (attendee.blank? ? '' : attendee.id)
      }
    }
  end

  def user_attendee
    attendee.user_attendees.where(user: user).first
  end

  def cancel_by_attendee
    return update_attributes(attendee_id: nil) if Time.now < date_start.advance(hours: -user.cancel_delay)

    errors.add :base, :not_in_cancel_delay, { delay: "#{user.cancel_delay}H" }
    destroy if event_type.is_available && !user.cancel_reopen
  end
end

app/controllers/slots_controller.rb
class SlotsController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[book booking]
  before_action :authenticate_attendee!, only: %i[book]
  before_action :authenticate_attendee!, only: %i[cancel], unless: -> { user_signed_in? }
  load_and_authorize_resource

  # GET /slots/1
  # GET /slots/1.json
  def show; end

  # GET /slots/new
  def new
    @attendees = current_user.attendees
    @attendee = current_user.attendees.new
    @start = DateTime.parse(params[:date_start]) if params[:date_start]
    @end = DateTime.parse(params[:date_end]) if params[:date_end]
    @slot = @attendee.slots.build
    @slot.user = current_user
  end

  # GET /slots/1/edit
  def edit
    @attendees = current_user.attendees
  end

  # GET /slots/id/book
  def book; end

  # POST /slots/id/booking
  def booking
    respond_to do |format|
      if @slot.update(slot_params)
        format.html do
          if attendee_signed_in?
            @slot.user.attendees << current_attendee unless @slot.user.attendees.include?(current_attendee)
            redirect_to prepare_slot_path(@slot.user.slug, @slot), notice: I18n.t(:slot_booked, scope: %i[flashes slots booking])
          else
            redirect_to new_attendee_registration_path(slot: @slot.id), alert: I18n.t(:subscribe_first, scope: %i[flashes slots booking])
          end
        end
        format.json { render json: { status: :ok } }
      else
        format.html { render :book }
        format.json { render json: @slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /slots
  # POST /slots.json
  def create
    @slot = current_user.slots.new(slot_params)
    respond_to do |format|
      if @slot.save
        format.html { redirect_to slot_path(@slot.user.slug, @slot), notice: 'Slot was successfully created.' }
        format.json { render json: @slot, status: :created }
      else
        format.html do
          @attendees = current_user.attendees
          render :new
        end
        format.json { render json: @slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /slots/1
  # PATCH/PUT /slots/1.json
  def update
    respond_to do |format|
      if @slot.update(slot_params)
        format.html do
          if attendee_signed_in?
            @slot.user.attendees << current_attendee unless @slot.user.attendees.include?(current_attendee)
            redirect_to attendee_agenda_path, notice: 'Slot was successfully updated.'
          else
            @slot.user.attendees << @slot.attendee unless @slot.user.attendees.include?(@slot.attendee)
            redirect_to slot_path(@slot.user.slug, @slot), notice: 'Slot was successfully updated.'
          end
        end
        format.json { render json: { status: :ok } }
      else
        @attendees = current_user.attendees
        format.html { render :edit }
        format.json { render json: @slot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /slots/1
  # DELETE /slots/1.json
  def destroy
    @slot.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Slot was successfully destroyed.' }
      format.json { head :no_content }
      format.js { head :no_content }
    end
  end

  # PUT /slots/1/cancel
  # PUT /slots/1/cancel.json
  def cancel
    if attendee_signed_in?
      respond_to do |format|
        if @slot.cancel_by_attendee
          format.html do
            redirect_to attendee_agenda_path, notice: 'Slot was successfully canceled.'
          end
          format.json { head :no_content }
        else
          format.html do
            redirect_to attendee_agenda_path, alert: @slot.errors.full_messages.join(', ')
          end
          format.json { render json: @slot.errors, status: :unprocessable_entity }
        end
      end
    else
      @slot.update_attribute :attendee_id, nil
      respond_to do |format|
        format.html do
          redirect_to user_agenda_path(current_user), notice: 'Slot was successfully canceled.'
        end
        format.json { head :no_content }
      end
    end
  end

  private

  # Never trust parameters from the scary internet, only allow the white list through.
  def slot_params
    params.require(:slot).permit :date_start, :date_end, :user, :attendee_id, :event_type_id,
                                 :notes, :on_time, :behaviour
  end

  def current_ability
    @current_ability ||= AbilityAttendee.new if attendee_signed_in?
    @current_ability ||= Ability.new(current_user)
  end
end

app/views/slots/_form.html.erb
<%= form_with(model: slot, local: true) do |form| %>

  <% if slot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(slot.errors.count, "error") %> prohibited this slot from being saved:</h2>

      <ul>
        <% slot.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <% if form.object.persisted? %>
    <div class="container">
      <div class="row">
        <div class="col-sm-4 offset-sm-2 col-lg-3 offset-lg-3 text-center">
          <%= time_tag form.object.date_start %>
        </div>
        <div class="col-sm-4 col-lg-3 text-center">
          <%= time_tag form.object.date_end %>
        </div>
      </div>
    </div>
  <% end %>

  <div class="form-group text-center">
    <%= form.label :attendee_id %>
    <%= form.select :attendee_id, options_from_collection_for_select(@attendees, :id, :name) %>
  </div>

  <div class="text-center">
    <%= form.submit class: "btn btn-sm btn-success" %>
  </div>
<% end %>

app/views/slots/book.html.erb
<h1 class="text-center mt-0">
  <%= t(:book_slot) %>
</h1>

<h2 class="text-center">
  <small>
    <%= t(:with) %>
  </small>
  <%= @slot.user.name %>
</h2>

<%= form_with(model: @slot, local: true, url: booking_slot_path(@slot.user.slug, @slot.id)) do |form| %>
  <%= form.hidden_field :attendee_id, value: attendee_signed_in? ? current_attendee.id : nil %>

  <div class="container">
    <div class="row">
      <div class="col-sm-4 offset-sm-2 col-lg-3 offset-lg-3 text-center">
        <%= time_tag form.object.date_start %>
      </div>
      <div class="col-sm-4 col-lg-3 text-center">
        <%= time_tag form.object.date_end %>
      </div>
    </div>

    <div class="form-group text-center mt-2">
      <%= form.submit t(:book), class: "btn btn-md btn-success" %>
    </div>
  </div>
<% end %>

<div class="text-center">
  <%= link_to user_profile_path(@slot.user.slug) do %>
    Annuler et retour profil de <%= @slot.user.name %>
  <% end %>
</div>

app/views/slots/edit.html.erb
<h1>Editing Slot</h1>

<%= render 'form', slot: @slot %>

app/views/slots/new.html.erb
<h1>New Slot</h1>

<%= render 'form', slot: @slot %>

<%= link_to 'Back', slots_path %>

app/views/slots/show.html.erb
<h1 class="text-center mt-0">
  <%= t(@slot.event_type.label, scope: :event_types) %>
</h1>

<div class="row">
  <div class="col-sm-4 offset-sm-2 col-lg-3 offset-lg-3 text-center">
    <%= time_tag @slot.date_start %>
  </div>
  <div class="col-sm-4 col-lg-3 text-center">
    <%= time_tag @slot.date_end %>
  </div>
</div>

<% if @slot.attendee.present? %>
  <h2 class="text-center">
    <small>
      <%= t(:with) %>
    </small>
    <%= link_to @slot.attendee.name, user_attendee_path(current_user.slug, @slot.user_attendee) %>
  </h2>
<% end %>
<%= form_with model: @slot do |form| %>
  <div class="row">
    <div class="col-md-10">
      <div class="mini-trix mb-3">
        <h3 class='mb-0 mt-0'>
          <%= form.label :notes, t('.notes') %>
        </h3>
        <%= form.rich_text_area :notes %>
      </div>
    </div>
    <div class="col-md-2">
      <h3>
        <%= t('.on_time') %>
      </h3>

      <label>
        <%= form.radio_button :on_time, :ok, class: 'hide' %>
        <span class="fas fa-smile fa-2x"></span>
      </label>

      <label>
        <%= form.radio_button :on_time, :neutral, class: 'hide' %>
        <span class="fas fa-meh fa-2x"></span>
      </label>

      <label>
        <%= form.radio_button :on_time, :bad, class: 'hide' %>
        <span class="fas fa-frown fa-2x"></span>
      </label>

      <label>
        <%= form.radio_button :on_time, :danger, class: 'hide' %>
        <span class="fas fa-angry fa-2x"></span>
      </label>

      <h3>
        <%= t('.behaviour') %>
      </h3>
      <label>
        <%= form.radio_button :behaviour, :ok, class: 'hide' %>
        <span class="fas fa-smile fa-2x"></span>
      </label>
      <label>
        <%= form.radio_button :behaviour, :neutral, class: 'hide' %>
        <span class="fas fa-meh fa-2x"></span>
      </label>
      <label>
        <%= form.radio_button :behaviour, :bad, class: 'hide' %>
        <span class="fas fa-frown fa-2x"></span>
      </label>
      <label>
        <%= form.radio_button :behaviour, :danger, class: 'hide' %>
        <span class="fas fa-angry fa-2x"></span>
      </label>
    </div>
  </div>
  <div class="row">
    <div class="col-12">
    <%= form.submit :save, class: 'btn btn-md btn-success btn-block mt-2' %>
    </div>
  </div>
<% end %>