config/routes.rb
Rails.application.routes.draw do

  resources :event_types, except: %i(show)

  devise_for :attendees, controllers: { registrations: 'registrations' }
  scope "attendees" do
    get :agenda, to: 'attendees#agenda', as: :attendee_agenda
  end
  resources :attendees, only: %i() do
    resources :slots, only: %i() do
      member do
        put :cancel
      end
    end
  end

  scope module: 'administration', as: 'admin', path: 'admin' do
    get 'dashboard/index', as: :dashboard
    get 'dashboard/settings', as: :settings
    patch 'settings', to: 'settings#update', as: :update_settings
    delete 'delete_image', to: 'settings#delete_image'
    resources :servers, except: :show
    resources :users, except: :show
    authenticate :admin do
      require 'sidekiq/web'
      mount Sidekiq::Web => '/sidekiq'
    end
  end
  devise_for :admins

  resources :user, param: :slug do
    resources :user_attendees, as: :attendees
    get '/', to: 'users#profile', as: :profile
    get '/agenda', to: 'users#agenda', as: :agenda
    get '/events', to: 'users#events', as: :user_events
  end
  scope "user/:slug" do
    resources :slots, except: %i(index) do
      member do
        put :cancel
        get :book
        patch :booking
      end
    end
  end

  resources :servers, only: %i(index show), constraints: { format: :json }

  # Used by server connection of other servers
  get 'users', to: 'users#index', constraints: { format: :json }

  devise_for :users, controllers: { registrations: 'registrations' }
  devise_scope :user do
    delete 'delete_image', to: 'registrations#delete_image'
  end
  get 'home', to: 'home#index'
  get 'privacy', to: 'home#privacy', as: :privacy
  get 'legal', to: 'home#legal', as: :legal
  get 'tos', to: 'home#tos', as: :tos
  get 'credits', to: 'home#credits', as: :credits
  get 'security', to: 'home#security', as: :security
  get 'agenda', to: 'home#agenda', as: :agenda
  get 'decentralize', to: 'home#decentralize', as: :decentralize
  root to: "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user_attendee.rb
class UserAttendee < ApplicationRecord
  belongs_to :user
  belongs_to :attendee
end

app/controllers/user_attendees_controller.rb
class UserAttendeesController < ApplicationController
  load_and_authorize_resource through: :current_user

  # GET /user_attendees
  # GET /user_attendees.json
  def index
    @user_attendees = current_user.user_attendees.includes(:attendee)
  end

  # GET /user_attendees/1
  # GET /user_attendees/1.json
  def show
    @attendee = @user_attendee.attendee
    @meetings = @attendee.slots.where(user: current_user).order('date_start DESC')
    @on_time = @attendee.on_time
    @behaviour = @attendee.behaviour
    respond_to do |format|
      format.json do
        render json: @attendee.as_json
      end
      format.html do
        render :show
      end
    end
  end

  # GET /user_attendees/new
  def new
    @attendee = Attendee.new
    @user_attendee = current_user.user_attendees.new(attendee: @attendee)
  end

  # GET /user_attendees/1/edit
  def edit
    @attendee = @user_attendee.attendee
  end

  # POST /user_attendees
  # POST /user_attendees.json
  def create
    @attendee = Attendee.new(attendee_params)
    respond_to do |format|
      if @attendee.valid? && @attendee.save
        current_user.attendees << @attendee
        format.html { redirect_to @user_attendee, notice: 'User attendee was successfully created.' }
        format.js do
          render json: { attendee: @attendee.as_json, status: :created }.to_json
        end
      else
        format.html { render :new }
        format.json { render json: @user_attendee.errors.merge(@attendee.errors).full_messages.join(', '), status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_attendees/1
  # PATCH/PUT /user_attendees/1.json
  def update
    respond_to do |format|
      if @user_attendee.attendee.update(attendee_params)
        format.html { redirect_to @user_attendee, notice: 'User attendee was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_attendee }
      else
        @attendee = @user_attendee.attendee
        format.html { render :edit }
        format.json { render json: @user_attendee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_attendees/1
  # DELETE /user_attendees/1.json
  def destroy
    @attendee = @user_attendee.attendee
    @user_attendee.destroy
    if @attendee.encrypted_password.blank? && @attendee.users.blank?
      @attendee.destroy
    end
    respond_to do |format|
      format.html { redirect_to user_attendees_url, notice: 'Attendee relation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def attendee_params
    params.require(:attendee).permit :email, :firstname, :lastname, :phone
  end
end

app/views/user_attendees/_form.html.erb
<div class="form-group">
  <%= form.label :firstname %><br />
  <%= form.text_field :firstname, autocomplete: "firstname", autofocus: true, class: 'form-control' %>
</div>

<div class="form-group">
  <%= form.label :lastname %><br />
  <%= form.text_field :lastname, autocomplete: "lastname", class: 'form-control' %>
</div>

<% if form.object.encrypted_password.blank? %>
  <div class="form-group">
    <%= form.label :email %><br />
    <%= form.text_field :email, autocomplete: "email", class: 'form-control' %>
  </div>
<% else %>
  <div class="form-group">
    <div class="input-group col-3 ml-0 pl-0">
      <div class="input-group-prepend">
        <span class="input-group-text">
          Email
        </span>
      </div>
      <input type="text" class="form-control" aria-label="email" value="<%= attendee.email %>" disabled>
    </div>
    <small>
      This account has been claimed by its owner, you cannot modify this field.
    </small>
  </div>
<% end %>

<% if form.object.encrypted_password.blank? || form.object.phone.blank? %>
  <div class="form-group">
    <%= form.label :phone %><br />
    <%= form.text_field :phone, autocomplete: "phone", class: 'form-control' %>
  </div>
<% else %>
  <div class="form-group">
    <div class="input-group col-3 ml-0 pl-0">
      <div class="input-group-prepend">
        <span class="input-group-text">
          Phone
        </span>
      </div>
      <input type="text" class="form-control" aria-label="phone" value="<%= attendee.phone %>" disabled>
    </div>
    <small>
      This account has been claimed by its owner, you cannot modify this field.
    </small>
  </div>
<% end %>

<div class="form-group">
  <%= form.submit class: 'btn btn-md btn-success' %>
</div>

app/views/user_attendees/edit.html.erb
<h1>Editing User Attendee</h1>

<%= form_with(model: @attendee, local: true, url: user_attendee_path(current_user)) do |form| %>
  <% if @attendee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attendee.errors.count, "error") %> prohibited this attendee from being saved:</h2>

      <ul>
        <% @attendee.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= render 'form', attendee: @attendee, user_attendee: @user_attendee, form: form %>
<% end %>

<%= link_to 'Show', @user_attendee %> |
<%= link_to 'Back', user_attendees_path %>

app/views/user_attendees/index.html.erb
<h1 class="m-0">
  <%= t(:attendees, scope: :users) %>
</h1>

<%= link_to new_user_attendee_path, class: 'btn btn-success btn-sm' do %>
  Add attendee
<% end %>

<div class="table-responsive mt-2">
  <table class="table table-sm table-hover table-dark">
    <thead>
      <tr>
        <th></th>
        <th>Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th>Nb RDV</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @user_attendees.each do |user_attendee| %>
        <tr>
          <td class="text-center">
            <span class="fas fa-user-circle fa-2x"></span>
          </td>
          <td>
            <%= user_attendee.attendee.name %>
          </td>
          <td>
            <%= link_to user_attendee.attendee.email, "mailto:#{user_attendee.attendee.email}" %>
          </td>
          <td>
            <%= link_to user_attendee.attendee.phone, "tel:#{user_attendee.attendee.phone}" %>
          </td>
          <td>
            <%= user_attendee.attendee.slots_with(current_user) %>
          </td>
          <td class="text-right">
            <%= link_to edit_user_attendee_path(current_user, user_attendee), class: 'btn btn-sm btn-secondary' do %>
              <span class="fas fa-edit"></span>
              <%= t(:edit) %>
            <% end %>
            <%= link_to user_attendee_path(current_user, user_attendee), class: 'btn btn-sm btn-secondary' do %>
              <span class="fas fa-eye"></span>
              <%= t(:show) %>
            <% end %>

            <%= link_to user_attendee_path(current_user, user_attendee), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger" do %>

              <span class="fas fa-trash"></span>
              <%= :destroy %>
            <% end %>

          </td>

        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/user_attendees/new.html.erb
<h1>New User Attendee</h1>

<%= form_with(model: @attendee, local: true, url: user_attendees_path(current_user)) do |form| %>
  <% if @attendee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@attendee.errors.count, "error") %> prohibited this attendee from being saved:</h2>

      <ul>
        <% @attendee.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= render 'form', attendee: @attendee, user_attendee: @user_attendee, form: form %>
<% end %>

<%= link_to 'Back', user_attendees_path %>

app/views/user_attendees/show.html.erb
<div class="row">
  <div class="col-md-10">
    <h1 class="mt-0">
      <%= @attendee.name %>
    </h1>
  </div>
  <div class="col-md-2 text-right">
    <%= link_to edit_user_attendee_path(@user_attendee), class: 'btn btn-md btn-info btn-block' do %>
      <span class="fas fa-edit"></span>
      <%= t(:edit) %>
    <% end %>

  </div>
</div>

<div class="row">
  <div class="col-md-10">
    <%= @attendee.description %>
    <% if @meetings.any? %>
      <h2 class="mt-0">
        Last meeting
      </h2>
      <% if @meetings.last.notes.present? %>
        <%= @meetings.last.notes %>
      <% else %>
        <i>No notes took on the last meeting</i>
      <% end %>

      <div class="row">
        <% @meetings.each do |meeting| %>
          <div class="col-sm-3">
            <%= link_to slot_path(meeting.user.slug, meeting) do %>
              <div class="card <%= meeting.date_start > Time.now ? 'bg-blue' : 'bg-dark' %> text-white mt-2">
                <div class="card-body p-2">

                  <%= time_tag meeting.date_start %>
                  <br>
                  <small>
                    <%= distance_of_time_in_words(meeting.date_end, meeting.date_start) %>
                  </small>

                </div>
              </div>
            <% end %>

          </div>
        <% end %>
      </div>

    <% end %>
  </div>
  <div class="col-md-2">
    <hr>
    <h2>
      On time
    </h2>
    <%= display_on_time(@on_time) %>

    <h2>Behaviour</h2>
    <%= display_on_time(@behaviour) %>

    <h2>Stats</h2>
    <%= @meetings.count %> <%= t(:meetings) %>
  </div>