config/routes.rb
Rails.application.routes.draw do

  resources :event_types, except: %i(show)

  devise_for :attendees, controllers: { registrations: 'registrations' }
  scope "attendees" do
    get :agenda, to: 'attendees#agenda', as: :attendee_agenda
  end
  resources :attendees, only: %i() do
    resources :slots, only: %i() do
      member do
        put :cancel
      end
    end
  end

  scope module: 'administration', as: 'admin', path: 'admin' do
    get 'dashboard/index', as: :dashboard
    get 'dashboard/settings', as: :settings
    patch 'settings', to: 'settings#update', as: :update_settings
    delete 'delete_image', to: 'settings#delete_image'
    resources :servers, except: :show
    resources :users, except: :show
    authenticate :admin do
      require 'sidekiq/web'
      mount Sidekiq::Web => '/sidekiq'
    end
  end
  devise_for :admins

  resources :user, param: :slug do
    resources :user_attendees, as: :attendees
    get '/', to: 'users#profile', as: :profile
    get '/agenda', to: 'users#agenda', as: :agenda
    get '/events', to: 'users#events', as: :user_events
  end
  scope "user/:slug" do
    resources :slots, except: %i(index) do
      member do
        put :cancel
        get :book
        patch :booking
      end
    end
  end

  resources :servers, only: %i(index show), constraints: { format: :json }

  # Used by server connection of other servers
  get 'users', to: 'users#index', constraints: { format: :json }

  devise_for :users, controllers: { registrations: 'registrations' }
  devise_scope :user do
    delete 'delete_image', to: 'registrations#delete_image'
  end
  get 'home', to: 'home#index'
  get 'privacy', to: 'home#privacy', as: :privacy
  get 'legal', to: 'home#legal', as: :legal
  get 'tos', to: 'home#tos', as: :tos
  get 'credits', to: 'home#credits', as: :credits
  get 'security', to: 'home#security', as: :security
  get 'agenda', to: 'home#agenda', as: :agenda
  get 'decentralize', to: 'home#decentralize', as: :decentralize
  root to: "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!
  skip_authorization_check

  layout 'public'

  def index
    @users = User.last(2)
    @settings = Admin::Setting.first
    @home_disclaimer = @settings.home_disclaimer
  end

  def privacy
    @privacy = Admin::Setting.first.privacy
  end

  def legal
    @legal = Admin::Setting.first.legal
  end

  def tos
    @tos = Admin::Setting.first.tos
  end

  def credits; end

  def security; end
end

app/views/home/agenda.html.erb
<h1 class="mt-0 mb-0">
  <%= t(:agenda) %>
</h1>

<h2>
  <%= t(:title, scope: %i(home index)) %>
</h2>

<div class="row">
  <div class="col-sm-2 order-md-1 order-2">
    <%= image_pack_tag "undraw_calendar_dutt.svg", width: '100%' %>
  </div>
  <div class="col-sm-4 order-md-2 order-1">
    <h3>
      <%= t(:arg1, scope: %i(home index agenda)) %>
    </h3>
    <p>
      <%= t(:arg1_explain, scope: %i(home index agenda)) %>
      <br>
    </p>
    <h4>
      <%= t(:arg6, scope: %i(home agenda)) %>
    </h4>
    <p>
      <%= t(:arg6_explain, scope: %i(home agenda)) %>
    </p>
  </div>

  <div class="col-sm-2 order-md-3 order-4">
    <%= image_pack_tag "undraw_Booked_j7rj.svg", width: '100%' %>
  </div>
  <div class="col-sm-4 order-md-4 order-3">
    <div class="row">
      <div class="col">
        <h3>
          <%= t(:arg2, scope: %i(home index agenda)) %>
        </h3>
        <p>
          <%= t(:arg2_explain, scope: %i(home index agenda)) %>
        </p>
      </div>
    </div>
  </div>

</div>

<div class="row mt-3">
  <div class="col-sm-2 order-md-1 order-2">
    <%= image_pack_tag "undraw_profile_6l1l.svg", width: '100%' %>
  </div>
  <div class="col-sm-4 order-md-2 order-1">
    <h3>
      <%= t(:arg4, scope: %i(home index agenda)) %>
    </h3>
    <p>
      <%= t(:arg4_explain, scope: %i(home index agenda)) %>
    </p>
    <%= t(:arg4_explain_more_html, scope: %i(home index agenda)) %>
  </div>

  <div class="col-sm-2 order-md-3 order-4">
    <%= image_pack_tag "undraw_timeline_9u4u.svg", width: '100%' %>
  </div>
  <div class="col-sm-4 order-md-4 order-3">
    <h3>
      <%= t(:arg3, scope: %i(home index agenda)) %>
    </h3>
    <p>
      <%= t(:arg3_explain, scope: %i(home index agenda)) %>
    </p>
  </div>
</div>


<div class="row mt-3">
  <div class="col-sm-2 order-md-1 order-2">
    <%= image_pack_tag "undraw_grades_j6jn.svg", width: '100%' %>
  </div>
  <div class="col-sm-4 order-md-2 order-1">
    <h3>
      <%= t(:arg5, scope: %i(home agenda)) %>
    </h3>
    <p>
      <%= t(:arg5_explain, scope: %i(home agenda)) %>
    </p>
  </div>
  <div class="col-sm-6 order-3">
    <h3>Screenshots</h3>
    <div class="flip-wrapper js-modal" data-modal-content-id="modal-agenda" data-modal-describedby-id="modal_description" data-modal-close-text="<%= t(:close) %>" data-modal-close-title="<%= t(:close) %>">
      <div class="flipper">
        <%= image_pack_tag "screenshots/agenda-light.png", width: '100%', class: 'front' %>
        <%= image_pack_tag "screenshots/agenda-dark.png", width: '100%', class: 'back' %>
      </div>
    </div>
  </div>
</div>

<div id="modal-agenda" class="hidden">

  <div class="js-carrousel relative" id="modal-carousel-agenda">
    <div class="js-carrousel__container mod--hidden"
     data-carrousel-btn-previous-img="left.svg"
     data-carrousel-btn-next-img="right.svg"
     data-carrousel-btn-previous-text="< Previous"
     data-carrousel-btn-next-text="Next >"
     data-carrousel-prefix-class="news"
     data-carrousel-span-text-class="invisible"
     data-carrousel-transition="slide"
     data-carrousel-existing-hx="h3">

      <div class="js-carrousel__content">
        <h3>Agenda page</h3>
        <p>
          <%= image_pack_tag "screenshots/agenda-light.png", width: '100%', alt: "Agenda page view" %>
        </p>
      </div>
      <div class="js-carrousel__content">
        <h3>Agenda page - dark mode</h3>
        <p>
          <%= image_pack_tag "screenshots/agenda-dark.png", width: '100%', alt: "Agenda page view in dark mode" %>
        </p>
      </div>
      <div class="js-carrousel__content">
        <h3>Parameters page</h3>
        <p>
          <%= image_pack_tag "screenshots/parameters-light.png", width: '100%', alt: "Let you configure your agenda, its automation, cancelation strategies & event types." %>
        </p>
      </div>
      <div class="js-carrousel__content">
        <h3>Parameters page - dark mode</h3>
        <p>
          <%= image_pack_tag "screenshots/parameters-dark.png", width: '100%', alt: "Let you configure your agenda, its automation, cancelation strategies & event types." %>
        </p>
      </div>
      <div class="js-carrousel__content">
        <h3>Admin dashboard</h3>
        <p>
          <%= image_pack_tag "screenshots/admin-light.png", width: '100%', alt: "Fast situation overview of the website, important pages, users and federated servers." %>
        </p>
      </div>
      <div class="js-carrousel__content">
        <h3>Admin dashboard - dark mode</h3>
        <p>
          <%= image_pack_tag "screenshots/admin-dark.png", width: '100%', alt: "Fast situation overview of the website, important pages, users and federated servers." %>
        </p>
      </div>
    </div>
  </div>

</div>
<div id="modal_description" class="hidden">
  <p>
    Voici l'interface principale de votre Agenda.
    A gauche une zone pour prendre des notes générales.
    A droite, prenant 80% de l'écran, l'agenda, présenté par jours travaillés, par semaine, ou par mois.
  </p>
</div>

app/views/home/credits.html.erb
<h1>
  <span class="fas fa-heart"></span>
  Credits
</h1>

<div class="row">
  <div class="col-sm">
    <h2>Technologies / code</h2>
    <ul>
      <li>
        <a href="https://rubyonrails.org" rel="noopener">
          Ruby on Rails
        </a>
      </li>
      <li>
        <a href="https://www.ruby-lang.org" rel="noopener">
          Ruby
        </a>
      </li>
      <li>
        <a href="https://fullcalendar.io" rel="noopener">
        Fullcalendar
        </a>
      </li>
      <li>
        <a href="https://getbootstrap.com/" rel="noopener">
          Twitter Bootstrap
        </a>
      </li>
      <li>
        <a href="https://fontawesome.com" rel="noopener">
          FontAwesome
        </a>
      </li>
      <li>
        <a href="https://van11y.net" rel="noopener">
          https://van11y.net
        </a>
        <br>
        <ul>
          <li>van11y-accessible-carrousel-aria</li>
          <li>van11y-accessible-modal-window-aria</li>
        </ul>
      </li>
    </ul>
  </div>
  <div class="col-sm-3">
    <h2>Design / UX</h2>
    <ul>
      <li>
        <a href="https://undraw.co/" rel="noopener">
          Undraw
        </a>
      </li>
      <li>
        <a href="https://www.colourlovers.com/" rel="noopener">
          ColorLovers
        </a>
      </li>
      <li>
        <a href="http://paletton.com/" rel="noopener">
          Paleton
        </a>
      </li>
    </ul>
  </div>
  <div class="col-sm">
    <%= image_pack_tag "undraw_static_assets_rpm6.svg", width: '100%' %>
  </div>
</div>

app/views/home/decentralize.html.erb
<h1>
  <span class="fas fa-globe"></span>
  <%= t(:title, scope: %i(home index decentralized)) %>
</h1>

<div class="row">
  <div class="col-sm-2 order-md-1 order-2">
    <%= image_pack_tag "undraw_connected_world_wuay.svg", width: '100%' %>
  </div>
  <div class="col-sm-10 order-md-2 order-1">
    <h2>
      <%= t(:title, scope: %i(home decentralize what)) %>
    </h2>
    <p>
     Decentralisation means there are <strong>many different servers</strong>, linked or not between each other, running the service.
     <br>
     Decentralization, also called distributed architecture, is the opposite of centralized systems, where everything is on the same server.
     <br>
     In a distributed architecture each of thoses server are <strong>owned by different entities.</strong>
     <small>individuals, companies, associations, etc </small>
     <br>
     Each of thoses server runs the service on <strong>their own database</strong>.
     <br>
     Each of thoses server can have a customized version of the service.
    </p>
    <p>
      The power of decentralisation really shines when those servers are <i>connected</i> to each other, displaying information from each others without having to store it.
      <br>
      It is sometimes called a <strong>federated</strong> service.
    </p>
  </div>
</div>

<div class="row">
  <div class="col-sm-2 order-md-1 order-2">

  </div>
  <div class="col-sm-10 order-md-2 order-1">
    <h2>
      <%= t(:title, scope: %i(home decentralize why)) %>
    </h2>
  </div>
</div>
<div class="row">
  <div class="col-sm-2 order-md-1 order-2">
    <%= image_pack_tag "undraw_floating.svg", width: '100%' %>
  </div>
  <div class="col-sm-4 order-md-2 order-1">
    <h3>
      <%= t(:liberty, scope: %i(home decentralize why)) %>
    </h3>
    <p>
      Everyone can host its own server/service.
      <br>
      You are NOT bound to us. You are free.
    </p>
    <p>
      Everyone can leave a server and go to another one.
      <br>
      You are NOT bound to anyone. You are free.
    </p>
    <p>
      Every service can echo/distribute another one.
      <br>
      You can be a part of a community of peers.
    </p>
  </div>
  <div class="col-sm-2 order-md-3 order-4">
    <%= image_pack_tag "undraw_security_on.svg", width: '100%' %>
  </div>
  <div class="col-sm-4 order-md-4 order-3">
    <h3>
      <%= t(:security) %>
    </h3>
    <p class="mt-3">
     Thanks to decentralized architecture, we physically
     <ul>
      <li>reduce global indisponibility of the service</li>
      <li>shorten the range of attack on datas</li>
     </ul>
     Because all servers are independent, the mesh is stronger and one down does not affect the whole group.
    </p>
    <%= link_to security_path, class: 'btn btn-blue btn-block' do %>
      <%= t(:learn_more_security) %>
    <% end %>
  </div>
</div>

app/views/home/index.html.erb
<h1 class="mt-0 mb-0">
  <%= t(:appname) %>
</h1>

<h2>
  <%= t('.title') %>
</h2>
<p itemprop="about">
  <%= t('.liberty_has_no_price') %>
</p>

<hr>

<h2>
  <%= t('.last_subscribers') %>
</h2>
<div class="container-fluid" id="home_index">
  <% if @users.present? && @users.any? %>
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-4">
      <% @users.each do |user| %>
        <div class="col-sm-1 col-md-6 mb-1">
          <div class="card bg-blue">
            <div class="card-header">
              <%= link_to user_profile_path(user.slug) do %>
                <% if user.image.attached? %>
                  <%= image_tag user.image.variant(resize_to_limit: [64, 64]), { itemprop: 'image', alt: t(:image, scope: %i(users profile)) } %>
                <% end %>
                <%= user.name %>
              <% end %>
            </div>
            <div class="card-body">
              <%= user.description %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>

  <div id="other_users" class="row row-cols-1 row-cols-sm-2 row-cols-md-4 mt-2" data-title="Sur d'autres plateformes"></div>

  <% if @home_disclaimer.present? %>
    <div class="jumbotron text-center">
      <%= @home_disclaimer %>
    </div>
  <% end %>

  <div class="row mt-2">
    <div class="col-sm-6 order-md-1 order-2">
      <%= image_pack_tag "undraw_events_2p66.svg", width: '100%', alt: 'woman looking at a giant calendar filled with events' %>
    </div>
    <div class="col-sm-6 order-md-2 order-1 p-1">
      <h3>
        <%= t(:title, scope: %i(home index agenda)) %>
      </h3>
      <ul class="list-group">
        <li class="list-group-item">
          <h4 class="mb-0">
            <%= t(:arg1, scope: %i(home index agenda)) %>
          </h4>
          <small class="invisible-mobile">
            <%= t(:arg1_explain, scope: %i(home index agenda)) %>
          </small>
        </li>
        <li class="list-group-item">
          <h4 class="mb-0">
            <%= t(:arg2, scope: %i(home index agenda)) %>
          </h4>
          <small class="invisible-mobile">
            <%= t(:arg2_explain, scope: %i(home index agenda)) %>
          </small>
        </li>
        <li class="list-group-item">
          <h4 class="mb-0">
            <%= t(:arg3, scope: %i(home index agenda)) %>
          </h4>
          <small class="invisible-mobile">
            <%= t(:arg3_explain, scope: %i(home index agenda)) %>
          </small>
        </li>
        <li class="list-group-item">
          <h4 class="mb-0">
            <%= t(:arg4, scope: %i(home index agenda)) %>
          </h4>
          <small class="invisible-mobile">
            <%= t(:arg4_explain, scope: %i(home index agenda)) %>
          </small>
        </li>
      </ul>

      <div class="row mt-2">
        <div class="col <%= @settings.register_pro? ? 'pr-1' : ''%>">
          <%= link_to agenda_path, class: 'btn btn-lg btn-block btn-blue' do %>
            <span class="fas fa-info-circle"></span>
            <div class="visible-mobile"></div>
            <%= t('.know_more') %>
          <% end %>
        </div>
        <% if @settings.register_pro? %>
          <div class="col pl-1">
            <%= link_to new_user_registration_path, class: 'btn btn-lg btn-block btn-pink' do %>
              <%= t('.try_it') %>
              <span class="fas fa-chevron-circle-right"></span>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="row mt-2">
    <div class="col-sm-6 order-md-1 order-1">
      <h3>
        <%= t(:title, scope: %i(home index decentralized)) %>
      </h3>
      <ul class="list-group">
        <li class="list-group-item">
          <h4 class="mb-0">
            <%= t(:arg1, scope: %i(home index decentralized)) %>
          </h4>
          <small class="invisible-mobile">
            <%= t(:arg1_explain, scope: %i(home index decentralized)) %>
          </small>
        </li>
        <li class="list-group-item">
          <h4 class="mb-0">
            <%= t(:arg2, scope: %i(home index decentralized)) %>
          </h4>
          <small class="invisible-mobile">
            <%= t(:arg2_explain, scope: %i(home index decentralized)) %>
            <br>
            <%= t(:arg3_explain, scope: %i(home index decentralized)) %>
          </small>
        </li>
        <li class="list-group-item">
          <h4 class="mb-0">
            <%= t(:arg4, scope: %i(home index decentralized)) %>
          </h4>
          <small class="invisible-mobile">
            <%= t(:arg4_explain, scope: %i(home index decentralized)) %>
          </small>
        </li>
      </ul>
      <%= link_to decentralize_path, class: 'btn btn-lg btn-block btn-blue mt-2' do %>
        <span class="fas fa-info-circle"></span>
        <%= t('.know_more') %>
      <% end %>
    </div>
    <div class="col-sm-6 order-md-2 order-2">
      <%= image_pack_tag "undraw_connected_world_wuay.svg", width: '100%', alt: 'world map with distributed connections among countries' %>
    </div>
  </div>

  <div class="row mt-2">
    <div class="col-sm-6 order-md-1 order-2">
      <%= image_pack_tag "undraw_open_source_1qxw.svg", width: '100%', alt: 'two people working on a computer with a Creative Commons logo in background' %>
    </div>
    <div class="col-sm-6 order-md-2 order-1">
      <h3>
        <%= t(:title, scope: %i(home index open_source)) %>
      </h3>
      <%= t(:paragraph_html, scope: %i(home index open_source)) %>
    </div>
  </div>
</div>

app/views/home/legal.html.erb
<h1>Legal Mention</h1>
<h2>
  MIT LICENCE
</h2>

<div class="row">
  <div class="col-sm-9 order-md-1 order-1">
    <p>
    Copyright &copy; 2020 Gregory Durelle
    </p>
    <p>
    Permission is hereby granted, free of charge, to any person obtaining a copy
    of this software and associated documentation files (the "Software"), to deal
    in the Software without restriction, including without limitation the rights
    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
    copies of the Software, and to permit persons to whom the Software is
    furnished to do so, subject to the following conditions:
    <br><br>
    The above copyright notice and this permission notice shall be included in all
    copies or substantial portions of the Software.
    </p>
    <p>
    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
    SOFTWARE.
    </p>
  </div>
  <div class="col-sm-3 order-md-2 order-2">
    <%= image_pack_tag "logo-opensource.svg", width: '100%', alt: 'Open Source Initiative Logo' %>
  </div>
</div>

<hr>

<%= @legal %>

app/views/home/privacy.html.erb
<h1>
  <%= t(:privacy) %>
</h1>

<div class="row">
  <div class="col-sm-5 order-md-1 order-2">
    <%= image_pack_tag "undraw_gdpr.svg", width: '100%' %>
  </div>
  <div class="col-sm-7 order-md-2 order-1">
    <%= @privacy %>
  </div>
</div>

app/views/home/security.html.erb
<h1>
  <span class="fas fa-shield-alt"></span>
  <%= t(:security) %>
</h1>
<h2>
  <%= t(:liberty_has_no_price, scope: %i(home index)) %>
</h2>

<div class="row">
  <div class="col-sm-2 order-md-1 order-2">
    <%= image_pack_tag "undraw_security_on.svg", width: '100%' %>
  </div>
  <div class="col-sm-4 order-md-2 order-1">
    <h3>
      <%= t(:privacy_matters, scope: %i(home security)) %>
    </h3>
    <%= t(:privacy_arg_html, scope: %i(home security)) %>
  </div>
</div>

<div class="row mt-4">
  <div class="col-sm-2 order-md-1 order-2">
    <%= image_pack_tag "undraw_open_source_1qxw.svg", width: '100%' %>
  </div>
  <div class="col-sm-4 order-md-2 order-1">
    <h3>
      <%= t(:title, scope: %i(home security open_source)) %>
      <br>
      <small>
        <%= t(:subtitle, scope: %i(home security open_source)) %>
      </small>
    </h3>
    <%= t(:paragraph_html, scope: %i(home security open_source)) %>
  </div>

  <div class="col-sm-2 order-md-3 order-4">
    <%= image_pack_tag "undraw_connected_world_wuay.svg", width: '100%' %>
  </div>
  <div class="col-sm-4 order-md-4 order-3">
    <h3>
      <%= t(:title, scope: %i(home security decentralization)) %>
    </h3>
    <%= t(:paragraph_html, scope: %i(home security decentralization)) %>

    <%= link_to decentralize_path, class: 'btn btn-blue btn-block pt-1 pb-1' do %>
      <%= t(:more_about, scope: %i(home security decentralization)) %>
    <% end %>
  </div>
</div>

<div class="row mt-4">
  <div class="col-sm-2 order-md-1 order-2">
    <%= image_pack_tag "rails-logo.svg", width: '88%', class: 'white-shape' %>
  </div>
  <div class="col-sm-4 order-md-2 order-1">
    <h3>Ruby on Rails</h3>
    <%= t(:paragraph_html, scope: %i(home security framework)) %>
  </div>

  <div class="col-sm-2 order-md-3 order-4">
    <%= image_pack_tag "undraw_security.svg", width: '100%' %>
  </div>
  <div class="col-sm-4 order-md-4 order-3">
    <h3>
      <%= t(:title, scope: %i(home security encrypted)) %>
    </h3>
    <%= t(:paragraph_html, scope: %i(home security encrypted)) %>
  </div>
</div>

app/views/home/tos.html.erb
<h1>
  <%= t(:tos) %>
</h1>

<div class="row">
  <div class="col-sm-3 order-md-1 order-2">
    <%= image_pack_tag "undraw_terms_lso0.svg", width: '100%' %>
  </div>
  <div class="col-sm-9 order-md-2 order-1">
    <%= @tos %>
  </div>
</div>